### ISSUE TITLE
[IDEA] Upgrade Random Generator

### ISSUE THREAD

**Issue by Agentew04** [Inaciocb/PasswordGenerator#2]
Shouldn't the app use the more modern `std::mt19937` and `std::uniform_int_distribution` solutions as it is more of a security focused application(password generator)?

A little bit of code explaining how to use this API:
```cpp
#include <random>

//...

int seed = time(0) * 1000 + clock();
auto dice = std::bind(std::uniform_int_distribution<>(1,6),std::mt19937(seed));
int twoDiceRoll = dice() + dice();
```

Just tweaking the `(1,6)` to the upper and lower bounds of the ASCII file should be enough to make it work on your app.

**Comment by Inaciocb** [comment]
Good evening Rodrigo,
Thanks for the suggestion! However, I wonder if those changes would significantly improve the password strength (which is the bare purpose on the application) but I'll add them anyway since code upgrades are always welcome.
